# Generated by Django 3.2.18 on 2023-05-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('name_ru', models.CharField(max_length=355, null=True)),
                ('name_en', models.CharField(max_length=355, null=True)),
                ('name_fr', models.CharField(max_length=355, null=True)),
                ('name_ja', models.CharField(max_length=355, null=True)),
                ('name_ar', models.CharField(max_length=355, null=True)),
                ('name_zh_cn', models.CharField(max_length=355, null=True)),
                ('name_de', models.CharField(max_length=355, null=True)),
                ('name_pt', models.CharField(max_length=355, null=True)),
                ('name_es', models.CharField(max_length=355, null=True)),
                ('name_tr', models.CharField(max_length=355, null=True)),
                ('name_it', models.CharField(max_length=355, null=True)),
                ('name_hi', models.CharField(max_length=355, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_ja', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh_cn', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('description_pt', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_tr', models.TextField(null=True)),
                ('description_it', models.TextField(null=True)),
                ('description_hi', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('name_ru', models.CharField(max_length=350, null=True)),
                ('name_en', models.CharField(max_length=350, null=True)),
                ('name_fr', models.CharField(max_length=350, null=True)),
                ('name_ja', models.CharField(max_length=350, null=True)),
                ('name_ar', models.CharField(max_length=350, null=True)),
                ('name_zh_cn', models.CharField(max_length=350, null=True)),
                ('name_de', models.CharField(max_length=350, null=True)),
                ('name_pt', models.CharField(max_length=350, null=True)),
                ('name_es', models.CharField(max_length=350, null=True)),
                ('name_tr', models.CharField(max_length=350, null=True)),
                ('name_it', models.CharField(max_length=350, null=True)),
                ('name_hi', models.CharField(max_length=350, null=True)),
                ('image', models.ImageField(upload_to='guids')),
                ('bio', models.TextField()),
                ('bio_ru', models.TextField(null=True)),
                ('bio_en', models.TextField(null=True)),
                ('bio_fr', models.TextField(null=True)),
                ('bio_ja', models.TextField(null=True)),
                ('bio_ar', models.TextField(null=True)),
                ('bio_zh_cn', models.TextField(null=True)),
                ('bio_de', models.TextField(null=True)),
                ('bio_pt', models.TextField(null=True)),
                ('bio_es', models.TextField(null=True)),
                ('bio_tr', models.TextField(null=True)),
                ('bio_it', models.TextField(null=True)),
                ('bio_hi', models.TextField(null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('city', models.ManyToManyField(related_name='guids', to='guid.City')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraction', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='languages')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOfGuid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guid_works')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='guid.guid')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('comment_ru', models.TextField(blank=True, null=True)),
                ('comment_en', models.TextField(blank=True, null=True)),
                ('comment_fr', models.TextField(blank=True, null=True)),
                ('comment_ja', models.TextField(blank=True, null=True)),
                ('comment_ar', models.TextField(blank=True, null=True)),
                ('comment_zh_cn', models.TextField(blank=True, null=True)),
                ('comment_de', models.TextField(blank=True, null=True)),
                ('comment_pt', models.TextField(blank=True, null=True)),
                ('comment_es', models.TextField(blank=True, null=True)),
                ('comment_tr', models.TextField(blank=True, null=True)),
                ('comment_it', models.TextField(blank=True, null=True)),
                ('comment_hi', models.TextField(blank=True, null=True)),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='guid.guid')),
            ],
        ),
        migrations.AddField(
            model_name='guid',
            name='language',
            field=models.ManyToManyField(related_name='guids', to='guid.Language'),
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cities')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guid.city')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField()),
                ('contact_link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='guid.city')),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='guid.guid')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='guid.language')),
            ],
        ),
    ]
