# Generated by Django 3.2.18 on 2023-03-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.ForeignKey(default=1, on_delete=models.SET('City deleted'), related_name='booking', to='guid.city'),
            preserve_default=False,
        ),
    ]
