# Generated by Django 3.2.18 on 2023-03-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
