# Generated by Django 3.2.18 on 2023-04-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='guid.city'),
        ),
    ]
