# Generated by Django 3.2.18 on 2023-03-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='description_cn',
            new_name='description_zh',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name_cn',
            new_name='name_zh',
        ),
        migrations.RenameField(
            model_name='guid',
            old_name='bio_cn',
            new_name='bio_zh',
        ),
        migrations.RenameField(
            model_name='guid',
            old_name='name_cn',
            new_name='name_zh',
        ),
    ]
