# Generated by Django 3.2.18 on 2023-03-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0002_booking_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_link',
            field=models.CharField(max_length=255),
        ),
    ]
