# Generated by Django 3.2.18 on 2023-03-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0002_auto_20230312_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='description_zh',
            new_name='description_zh_CN',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name_zh',
            new_name='name_zh_CN',
        ),
        migrations.RenameField(
            model_name='guid',
            old_name='bio_zh',
            new_name='bio_zh_CN',
        ),
        migrations.RenameField(
            model_name='guid',
            old_name='name_zh',
            new_name='name_zh_CN',
        ),
    ]
