# Generated by Django 3.2.18 on 2023-03-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0003_auto_20230312_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='description_zh_CN',
            new_name='description_zh_cn',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name_zh_CN',
            new_name='name_zh_cn',
        ),
        migrations.RenameField(
            model_name='guid',
            old_name='bio_zh_CN',
            new_name='bio_zh_cn',
        ),
        migrations.RenameField(
            model_name='guid',
            old_name='name_zh_CN',
            new_name='name_zh_cn',
        ),
    ]
