# Generated by Django 3.2.18 on 2023-04-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0003_alter_language_contraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='guid.language'),
        ),
    ]
