# Generated by Django 3.2.18 on 2023-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0004_auto_20230312_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.ImageField(null=True, upload_to='languages'),
        ),
        migrations.AlterField(
            model_name='guid',
            name='city',
            field=models.ManyToManyField(related_name='guids', to='guid.City'),
        ),
        migrations.AlterField(
            model_name='guid',
            name='language',
            field=models.ManyToManyField(related_name='guids', to='guid.Language'),
        ),
        migrations.AlterField(
            model_name='workofguid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guid_works'),
        ),
    ]
