# Generated by Django 3.2.18 on 2023-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0005_auto_20230323_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(upload_to='languages'),
        ),
    ]
