# Generated by Django 3.2.18 on 2023-03-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0006_alter_language_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ar',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_de',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_es',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_fr',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_hi',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_it',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ja',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_pt',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_tr',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_zh_cn',
            field=models.CharField(max_length=355, null=True),
        ),
    ]
