# Generated by Django 3.2.18 on 2023-05-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('location_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('location_en', models.CharField(blank=True, max_length=250, null=True)),
                ('location_fr', models.CharField(blank=True, max_length=250, null=True)),
                ('location_ja', models.CharField(blank=True, max_length=250, null=True)),
                ('location_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('location_zh_cn', models.CharField(blank=True, max_length=250, null=True)),
                ('location_de', models.CharField(blank=True, max_length=250, null=True)),
                ('location_pt', models.CharField(blank=True, max_length=250, null=True)),
                ('location_es', models.CharField(blank=True, max_length=250, null=True)),
                ('location_tr', models.CharField(blank=True, max_length=250, null=True)),
                ('location_it', models.CharField(blank=True, max_length=250, null=True)),
                ('location_hi', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('address_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('address_en', models.CharField(blank=True, max_length=250, null=True)),
                ('address_fr', models.CharField(blank=True, max_length=250, null=True)),
                ('address_ja', models.CharField(blank=True, max_length=250, null=True)),
                ('address_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('address_zh_cn', models.CharField(blank=True, max_length=250, null=True)),
                ('address_de', models.CharField(blank=True, max_length=250, null=True)),
                ('address_pt', models.CharField(blank=True, max_length=250, null=True)),
                ('address_es', models.CharField(blank=True, max_length=250, null=True)),
                ('address_tr', models.CharField(blank=True, max_length=250, null=True)),
                ('address_it', models.CharField(blank=True, max_length=250, null=True)),
                ('address_hi', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interesting_places')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_link', models.CharField(max_length=255)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='guid.city')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='guid.language')),
            ],
        ),
    ]
