# Generated by Django 3.2.18 on 2023-04-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guid', '0002_alter_booking_city'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='guid.city'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='guid.language'),
        ),
    ]
